# Generated by Django 4.0.2 on 2022-02-24 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardcomment',
            options={},
        ),
    ]
