# Generated by Django 4.0.2 on 2022-02-25 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_boardcomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardcomment',
            options={'managed': False},
        ),
    ]
